version: "3"

tasks:
  migrate:
      aliases:
        - mig
      desc: "Migrates db"
      cmds:
        - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  run:
    aliases:
      - r
    desc: "Run app"
    cmds:
      - go run ./cmd/sso --config=./config/local.yaml
  test-migrate:
      aliases:
        - test_mig
      desc: "Migrates test db"
      cmds:
       - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  run-tests:
    aliases:
      - rt
    desc: "Run tests"
    cmds:
      - go run ./cmd/sso --config=./config/local_tests.yaml



    